/**
 * Chapter summaries for the KJV Bible.
 * Each entry is a 1-2 sentence description of what happens in that chapter.
 * Array is 0-indexed: index 0 = chapter 1.
 */

export const CHAPTER_SUMMARIES: Record<string, string[]> = {
  'Genesis': [
    'The creation of the heavens and the earth in six days. God speaks light, sky, land, sea, plants, lights, creatures, and mankind into existence.',
    'God forms man from the dust and places him in the Garden of Eden. He creates woman from the man\'s rib. The institution of marriage.',
    'The serpent tempts Eve, Adam and Eve eat the forbidden fruit, and God pronounces judgment. They are expelled from the Garden of Eden.',
    'Cain murders his brother Abel. God marks Cain and sends him away. The line of Cain builds cities. Seth is born to Adam and Eve.',
    'The genealogy from Adam to Noah through Seth\'s line. Men begin to live hundreds of years. Enoch walks with God and is taken.',
    'Wickedness fills the earth. God determines to destroy mankind with a flood. Noah finds grace and is commanded to build an ark.',
    'Noah enters the ark with his family and the animals. The flood covers the earth for forty days. All life outside the ark perishes.',
    'The waters recede. Noah sends out a raven and a dove. The ark rests on Ararat. Noah exits and builds an altar. God promises never to flood the earth again.',
    'God blesses Noah and establishes the covenant of the rainbow. Noah plants a vineyard and is shamed by Ham. Canaan is cursed.',
    'The table of nations — the descendants of Shem, Ham, and Japheth spread across the earth after the flood.',
    'The Tower of Babel. Mankind builds a city and tower to make a name for themselves. God confuses their language and scatters them.',
    'God calls Abram to leave Ur and go to a land He will show him. Abram goes to Canaan, then to Egypt because of famine.',
    'Abram and Lot separate. Lot chooses the plain of Jordan near Sodom. God promises Abram all the land he can see.',
    'Four kings capture Sodom and take Lot. Abram rescues Lot with 318 trained servants. Melchizedek blesses Abram.',
    'God makes a covenant with Abram, promising countless descendants and the land. The covenant is sealed with a smoking furnace and burning lamp passing between animal halves.',
    'Sarai gives Hagar to Abram. Hagar conceives Ishmael. The angel of the LORD finds Hagar in the wilderness and promises her son will be a great nation.',
    'God renames Abram to Abraham and Sarai to Sarah. The covenant of circumcision is established. God promises a son through Sarah.',
    'Three visitors come to Abraham at Mamre. The LORD promises Sarah a son. Abraham intercedes for Sodom, bargaining from fifty righteous down to ten.',
    'Two angels visit Sodom. Lot hosts them. The men of Sodom surround the house. Sodom and Gomorrah are destroyed by fire. Lot\'s wife becomes a pillar of salt.',
    'Abraham sojourns in Gerar. Abimelech takes Sarah but God warns him in a dream. Abraham prays and Abimelech is healed.',
    'Isaac is born to Abraham and Sarah. Hagar and Ishmael are sent away. God provides for them in the wilderness. Abraham makes a covenant with Abimelech.',
    'God tests Abraham, commanding him to offer Isaac on Mount Moriah. Abraham obeys. God provides a ram in the thicket. The oath is confirmed.',
    'Sarah dies at age 127. Abraham purchases the cave of Machpelah from Ephron the Hittite to bury her.',
    'Abraham sends his servant to find a wife for Isaac. The servant meets Rebekah at the well. She returns and becomes Isaac\'s wife.',
    'Abraham marries Keturah. Abraham dies and is buried by Isaac and Ishmael. The generations of Ishmael. Esau and Jacob are born to Rebekah.',
    'Isaac sojourns in Gerar during famine. God renews the Abrahamic promise. Isaac digs wells and makes a covenant with Abimelech. Esau marries Hittite women.',
    'Jacob deceives Isaac to receive Esau\'s blessing. Rebekah helps Jacob disguise himself. Esau is furious and plans to kill Jacob.',
    'Isaac sends Jacob to Paddan-aram to find a wife. Jacob dreams of a ladder reaching heaven with angels ascending and descending. God confirms the covenant.',
    'Jacob arrives at Laban\'s house. He loves Rachel and serves seven years for her. Laban deceives him with Leah. Jacob serves seven more years for Rachel.',
    'Leah bears Reuben, Simeon, Levi, and Judah. Rachel gives Bilhah who bears Dan and Naphtali. Leah gives Zilpah who bears Gad and Asher.',
    'Rachel bargains for mandrakes. Leah bears Issachar, Zebulun, and Dinah. Rachel finally bears Joseph. Jacob asks Laban to let him go.',
    'Jacob prospers through selective breeding of Laban\'s flocks. God blesses him despite Laban\'s attempts to change his wages.',
    'Jacob flees from Laban with his family and flocks. Laban pursues and overtakes him. They make a covenant at Mizpah.',
    'Jacob sends messengers to Esau. He wrestles with God at Peniel and is renamed Israel. His hip is dislocated.',
    'Jacob and Esau meet and reconcile. Jacob settles at Succoth, then buys land near Shechem.',
    'Dinah is violated by Shechem. Simeon and Levi deceive the men of Shechem and slaughter them in revenge. Jacob rebukes his sons.',
    'God tells Jacob to go to Bethel. Rachel dies giving birth to Benjamin. Isaac dies at 180 years and is buried by Esau and Jacob.',
    'The descendants of Esau (Edom). The chiefs and kings of Edom listed.',
    'Joseph\'s dreams anger his brothers. They sell him to Ishmaelite traders. He is taken to Egypt. Jacob mourns, believing Joseph is dead.',
    'Judah and Tamar. Tamar disguises herself and conceives twins by Judah — Pharez and Zarah.',
    'Joseph serves Potiphar in Egypt. Potiphar\'s wife falsely accuses him. Joseph is thrown into prison.',
    'Joseph interprets the dreams of Pharaoh\'s butler and baker in prison. The butler is restored but forgets Joseph.',
    'Pharaoh dreams of seven fat cows eaten by seven lean cows, and seven full ears consumed by seven thin ears. Joseph interprets: seven years of plenty followed by seven years of famine. He is made ruler over Egypt.',
    'Joseph\'s brothers come to Egypt for grain. Joseph recognizes them but they do not recognize him. He accuses them of being spies and keeps Simeon.',
    'The famine worsens. Jacob reluctantly sends Benjamin to Egypt. Joseph receives them and weeps privately. He feasts with them.',
    'Joseph hides his silver cup in Benjamin\'s sack. The brothers are brought back. Judah pleads to take Benjamin\'s place.',
    'Joseph reveals himself to his brothers. He weeps and forgives them. He sends them to bring Jacob to Egypt.',
    'Jacob and his entire family journey to Egypt — seventy souls. Jacob meets Pharaoh. Joseph settles them in the land of Goshen.',
    'The famine continues. Joseph buys all the land of Egypt for Pharaoh. Jacob makes Joseph swear to bury him in Canaan.',
    'Jacob blesses Ephraim and Manasseh, placing the younger before the elder. Joseph protests but Jacob insists — God\'s choice overrides human custom.',
    'Jacob prophesies over his twelve sons. Judah receives the scepter promise. Jacob dies and is embalmed.',
    'Jacob is buried in the cave of Machpelah. Joseph reassures his brothers: "Ye thought evil against me; but God meant it unto good." Joseph dies at 110.',
  ],
  'Exodus': [
    'Israel multiplies in Egypt. A new Pharaoh enslaves them. Hebrew midwives defy Pharaoh\'s order to kill male infants.',
    'Moses is born, hidden in a basket, and found by Pharaoh\'s daughter. He grows up in the palace, kills an Egyptian, and flees to Midian.',
    'God appears to Moses in the burning bush. He reveals His name — I AM THAT I AM — and commissions Moses to deliver Israel from Egypt.',
    'Moses objects that no one will believe him. God gives him three signs. Aaron is appointed as Moses\' spokesman. They return to Egypt.',
    'Moses and Aaron confront Pharaoh: "Let my people go." Pharaoh increases the workload. The people blame Moses.',
    'God reassures Moses and renews His promise. The genealogy of Moses and Aaron through Levi.',
    'The first plague: water turned to blood. The second plague: frogs cover the land.',
    'The third plague: lice. The fourth plague: swarms of flies. Pharaoh begins to negotiate but hardens his heart.',
    'The fifth plague: livestock disease. The sixth plague: boils. Pharaoh\'s heart remains hard.',
    'The seventh plague: hail destroys crops and livestock in the field. Pharaoh admits sin but hardens his heart again.',
    'The eighth plague: locusts devour everything the hail left. The ninth plague: three days of thick darkness over Egypt.',
    'God announces the tenth plague — the death of the firstborn. Instructions for the Passover lamb and the feast of unleavened bread.',
    'The Passover night. The firstborn of Egypt die. Pharaoh sends Israel away. They plunder the Egyptians. 430 years of sojourn end.',
    'Israel crosses the Red Sea on dry ground. Pharaoh\'s army pursues and is drowned when the waters return.',
    'The Song of Moses and Miriam celebrate the victory at the sea. Bitter water at Marah is made sweet.',
    'God provides quail and manna in the wilderness. Manna falls six days; a double portion on the sixth for the Sabbath.',
    'Israel camps at Rephidim. Moses strikes the rock for water. Amalekites attack; Joshua fights while Moses holds up his hands.',
    'Jethro visits Moses. He advises Moses to appoint judges to help govern the people. Moses organizes a system of delegation.',
    'Israel arrives at Sinai. God descends on the mountain with thunder, lightning, and smoke. The people tremble. God speaks the Ten Commandments.',
    'The Ten Commandments: no other gods, no graven images, do not take God\'s name in vain, remember the Sabbath, honor parents, do not murder, do not commit adultery, do not steal, do not bear false witness, do not covet.',
    'Laws concerning servants, personal injuries, and property damage. The eye-for-eye principle established.',
    'Laws concerning theft, property, social responsibility, and the three annual feasts. God promises to send an angel before them.',
    'Moses ratifies the covenant. Seventy elders see God and eat and drink. Moses ascends Sinai for forty days.',
    'God gives detailed instructions for the tabernacle: the ark of the covenant, the mercy seat, the table of shewbread, and the golden lampstand.',
    'Instructions for the tabernacle curtains, boards, bars, and the veil separating the Holy Place from the Holy of Holies.',
    'The altar of burnt offering, the court of the tabernacle, and the oil for the lampstand.',
    'Instructions for the priestly garments: the ephod, breastplate with twelve stones, robe, and golden plate inscribed HOLINESS TO THE LORD.',
    'The consecration of Aaron and his sons. The daily offerings — two lambs, morning and evening.',
    'The altar of incense, the atonement money, the bronze laver, the anointing oil, and the incense recipe.',
    'Bezaleel and Aholiab appointed as master craftsmen. The Sabbath commandment reiterated. Moses receives the tablets written by God.',
    'The golden calf. While Moses is on Sinai, Aaron makes an idol. Moses descends, breaks the tablets, grinds the calf to powder. Three thousand die.',
    'Moses pleads for Israel. He asks to see God\'s glory. God passes by, proclaiming His name: merciful, gracious, longsuffering, and abundant in goodness and truth.',
    'The covenant is renewed. New tablets are cut. Moses\' face shines when he descends from the mountain.',
    'Moses assembles Israel and repeats the Sabbath command. Offerings are collected for the tabernacle.',
    'The people bring more than enough material. Bezaleel begins crafting the tabernacle components.',
    'The ark, mercy seat, table of shewbread, lampstand, altar of incense, and anointing oil are constructed.',
    'The altar of burnt offering, the laver, and the court of the tabernacle are constructed.',
    'An accounting of the materials used. The priestly garments are made exactly as commanded.',
    'The tabernacle is erected on the first day of the first month of the second year. Moses inspects and blesses the work.',
    'The glory of the LORD fills the tabernacle. The cloud covers it by day and fire by night. When the cloud moves, Israel moves.',
  ],
  'Psalms': [
    'Blessed is the man who walks not in the counsel of the ungodly. He is like a tree planted by rivers of water.',
    'Why do the heathen rage? The LORD has set His king upon Zion. Kiss the Son lest He be angry.',
    'A psalm of David fleeing Absalom. LORD, how are they increased that trouble me. God is a shield about me.',
    'A prayer for God to hear and answer. Thou hast put gladness in my heart.',
    'A morning prayer. Lead me, O LORD, in thy righteousness. Let all who trust in thee rejoice.',
    'A prayer in distress. O LORD, rebuke me not in thine anger. The LORD hath heard my weeping.',
    'David cries to God for deliverance from his persecutors. Let the wickedness of the wicked come to an end.',
    'The majesty of God\'s name in all the earth. What is man that thou art mindful of him? Crowned with glory and honour.',
    'David praises God for righteous judgment. The LORD is a refuge for the oppressed.',
    'Why standest thou afar off, O LORD? The wicked persecutes the poor. Arise, O LORD.',
    'In the LORD put I my trust. The LORD tries the righteous. Upon the wicked He rains snares.',
    'Help, LORD, for the godly man ceases. The words of the LORD are pure words, tried seven times.',
    'How long wilt thou forget me, O LORD? David trusts in God\'s mercy and sings of His dealing.',
    'The fool hath said in his heart, There is no God. They are all gone aside. None doeth good.',
    'LORD, who shall abide in thy tabernacle? He that walketh uprightly and speaketh truth in his heart.',
    'Preserve me, O God, for in thee do I put my trust. Thou wilt show me the path of life.',
    'A prayer of David. Hear the right, O LORD. Try my heart. Keep me as the apple of the eye.',
    'David praises God for deliverance from enemies. The LORD is my rock, my fortress, my deliverer.',
    'The heavens declare the glory of God. The law of the LORD is perfect, converting the soul.',
    'The LORD hear thee in the day of trouble. Some trust in chariots; we trust in the name of the LORD.',
    'The king shall joy in thy strength, O LORD. Thou hast given him his heart\'s desire.',
    'My God, my God, why hast thou forsaken me? A prophecy of the crucifixion — they pierced my hands and feet.',
    'The LORD is my shepherd; I shall not want. He leads me beside still waters and through the valley of the shadow of death.',
    'The earth is the LORD\'s. Who shall ascend the hill of the LORD? He that hath clean hands and a pure heart.',
    'Unto thee, O LORD, do I lift up my soul. Remember not the sins of my youth. Show me thy ways.',
    'Judge me, O LORD, for I have walked in integrity. Examine me and try my reins and my heart.',
    'The LORD is my light and my salvation; whom shall I fear? One thing have I desired — to dwell in the house of the LORD.',
    'Unto thee will I cry, O LORD my rock. The LORD is the strength of His people.',
    'Give unto the LORD the glory due unto His name. The voice of the LORD is powerful and full of majesty.',
    'A psalm of dedication. Weeping may endure for a night, but joy cometh in the morning.',
    'In thee, O LORD, do I put my trust. Into thine hand I commit my spirit.',
    'Blessed is he whose transgression is forgiven. David confesses his sin and God forgives.',
    'Rejoice in the LORD. Praise Him with harp and psaltery. By the word of the LORD were the heavens made.',
    'David blesses the LORD at all times. The angel of the LORD encamps around those who fear Him.',
    'Plead my cause, O LORD. Let those who seek my hurt be put to shame.',
    'The transgression of the wicked speaks within my heart. The lovingkindness of God is precious.',
    'Fret not thyself because of evildoers. Trust in the LORD and do good. Delight thyself in the LORD.',
    'A prayer in affliction. There is no soundness in my flesh because of my sin.',
    'I said I will take heed to my ways. LORD, make me to know my end. Every man at his best state is vanity.',
    'I waited patiently for the LORD. He put a new song in my mouth. Blessed is the man who trusts the LORD.',
    'Blessed is he that considers the poor. The LORD will deliver him in time of trouble.',
    'As the deer pants for water, so my soul thirsts for God. Why art thou cast down, O my soul? Hope in God.',
    'Send out thy light and thy truth. Why art thou cast down? Hope thou in God.',
    'We have heard with our ears, O God. Our fathers told us of the work thou didst in their days.',
    'My heart overflows with a good matter — a song for the king. Thy throne, O God, is forever.',
    'God is our refuge and strength, a very present help in trouble. Be still and know that I am God.',
    'O clap your hands, all ye people. God is gone up with a shout. Sing praises to our King.',
    'Great is the LORD in the city of our God. Walk about Zion and tell the towers thereof.',
    'Hear this, all ye people. No man can redeem his brother. God will redeem my soul from the grave.',
    'The Mighty God speaks and calls the earth. He reproves His people — not for sacrifices but for thankless hearts.',
    'David\'s great penitential psalm after his sin with Bathsheba. Create in me a clean heart, O God.',
    'Why boastest thou thyself in mischief, O mighty man? God shall destroy thee forever.',
    'The fool hath said in his heart, There is no God. They are corrupt and have done abominable iniquity.',
    'Save me, O God, by thy name. God is mine helper. He hath delivered me out of all trouble.',
    'Give ear to my prayer, O God. The words of his mouth were smoother than butter but war was in his heart.',
    'Be merciful unto me, O God, for man would swallow me up. When I am afraid, I will trust in thee.',
    'Be merciful unto me, O God. My soul is among lions. Awake, my glory. I will praise thee among the nations.',
    'Do ye judge uprightly? The righteous shall rejoice when he sees the vengeance. God judges in the earth.',
    'Deliver me from mine enemies. The mighty gather against me. Consume them in wrath.',
    'O God, thou hast cast us off. Give us help from trouble, for vain is the help of man.',
    'Hear my cry, O God. Lead me to the rock that is higher than I. I will abide in thy tabernacle forever.',
    'Truly my soul waiteth upon God. My salvation comes from Him. He only is my rock.',
    'O God, thou art my God; early will I seek thee. My soul thirsteth for thee in a dry and thirsty land.',
    'Hear my voice, O God, in my prayer. The righteous shall be glad in the LORD.',
    'Praise waiteth for thee, O God, in Zion. Thou crownest the year with thy goodness.',
    'Make a joyful noise unto God. Come and see the works of God. He is terrible in His doing toward the children of men.',
    'God be merciful unto us and bless us. Let the people praise thee, O God.',
    'Let God arise, let His enemies be scattered. A father of the fatherless. He gives the solitary a family.',
    'Save me, O God, for the waters are come in unto my soul. The zeal of thine house hath eaten me up.',
    'Make haste, O God, to deliver me. Let them be ashamed that seek after my soul.',
    'In thee, O LORD, do I put my trust. Thou art my hope from my youth. Cast me not off in old age.',
    'A psalm for Solomon. Give the king thy judgments, O God. He shall judge the poor and save the needy.',
    'Truly God is good to Israel. The wicked prosper, but their end is destruction. Asaph nearly stumbled at the injustice.',
    'O God, why hast thou cast us off forever? The enemy hath destroyed the sanctuary.',
    'Unto thee, O God, do we give thanks. In the hand of the LORD there is a cup of judgment.',
    'In Judah is God known. At thy rebuke, both the chariot and horse are cast into a dead sleep.',
    'I cried unto God. Will the Lord cast off forever? I will remember the works of the LORD.',
    'A parable of Israel\'s history. God\'s faithfulness despite the people\'s rebellion from Egypt to David.',
    'O God, the heathen have come into thine inheritance. Jerusalem is in ruins. How long, LORD?',
    'Give ear, O Shepherd of Israel. Restore us, O God. Turn us again and cause thy face to shine.',
    'Sing aloud unto God our strength. I am the LORD thy God who brought thee out of Egypt. Open thy mouth wide.',
    'God stands in the congregation of the mighty. He judges among the gods. Arise, O God, judge the earth.',
    'Keep not thou silence, O God. The enemies of Israel conspire together.',
    'How amiable are thy tabernacles, O LORD. Blessed are they that dwell in thy house. A day in thy courts is better than a thousand.',
    'LORD, thou hast been favorable to thy land. Mercy and truth are met together; righteousness and peace have kissed.',
    'Bow down thine ear, O LORD. There is none like thee among the gods.',
    'His foundation is in the holy mountains. Glorious things are spoken of thee, O city of God.',
    'O LORD God of my salvation, I have cried day and night before thee. My acquaintance is darkness.',
    'I will sing of the mercies of the LORD forever. The Davidic covenant — thy seed will I establish forever.',
    'LORD, thou hast been our dwelling place in all generations. Teach us to number our days.',
    'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.',
    'A song for the Sabbath. The righteous shall flourish like the palm tree.',
    'The LORD reigneth, He is clothed with majesty. The floods have lifted up their voice.',
    'O LORD God, to whom vengeance belongeth. How long shall the wicked triumph?',
    'O come, let us sing unto the LORD. Today if ye will hear His voice, harden not your heart.',
    'O sing unto the LORD a new song. The LORD reigneth. Let the earth rejoice.',
    'The LORD reigneth. He is exalted above all gods. Worship at His holy hill.',
    'O sing unto the LORD a new song. All the earth shall see the salvation of our God.',
    'The LORD reigneth — let the people tremble. He is holy.',
    'Make a joyful noise unto the LORD, all ye lands. Know that the LORD He is God.',
    'I will sing of mercy and judgment. I will behave wisely in a perfect way.',
    'Hear my prayer, O LORD. My days are consumed like smoke. But thou, LORD, shalt endure forever.',
    'Bless the LORD, O my soul, and forget not all His benefits. He forgives, heals, redeems, and crowns with lovingkindness.',
    'Bless the LORD, O my soul. God stretches out the heavens like a curtain. He waters the hills and makes grass to grow.',
    'O give thanks unto the LORD. He remembered His covenant with Abraham. Israel\'s history from Egypt to the promised land.',
    'Praise ye the LORD. Israel\'s rebellions despite God\'s mercies. Moses interceded. They forgot God their Saviour.',
    'O give thanks unto the LORD, for He is good. His mercy endureth forever. He gathered His people from the lands.',
    'A song of ascents. The LORD delivered me from distress. It is better to trust in the LORD than in princes.',
    'O give thanks unto the LORD. His mercy endureth forever. The stone which the builders refused is become the head of the corner.',
    'Blessed are the undefiled in the way. Thy word have I hid in mine heart. Teach me thy statutes. The longest psalm — 176 verses on the excellency of God\'s word.',
    'In my distress I cried unto the LORD. Woe is me that I dwell in the tents of Kedar.',
    'I will lift up mine eyes unto the hills. My help cometh from the LORD. He will not slumber.',
    'I was glad when they said unto me, Let us go into the house of the LORD. Pray for the peace of Jerusalem.',
    'Unto thee lift I up mine eyes, O thou that dwellest in the heavens. Have mercy upon us.',
    'If it had not been the LORD who was on our side — the waters had overwhelmed us.',
    'They that trust in the LORD shall be as mount Zion, which cannot be removed.',
    'When the LORD turned again the captivity of Zion, we were like them that dream. They that sow in tears shall reap in joy.',
    'Except the LORD build the house, they labour in vain. Children are an heritage of the LORD.',
    'Blessed is every one that feareth the LORD. Thy wife shall be as a fruitful vine.',
    'Many a time have they afflicted me from my youth. The plowers plowed upon my back.',
    'Out of the depths have I cried unto thee, O LORD. I wait for the LORD more than they that watch for the morning.',
    'LORD, my heart is not haughty. I have quieted myself as a child weaned of his mother.',
    'David\'s vow to find a dwelling place for the LORD. The LORD has chosen Zion.',
    'Behold, how good and how pleasant it is for brethren to dwell together in unity.',
    'Behold, bless ye the LORD, all ye servants of the LORD, which by night stand in the house of the LORD.',
    'O give thanks unto the LORD, for He is good. He made great lights. He smote Egypt and divided the Red Sea.',
    'By the rivers of Babylon we wept when we remembered Zion. How shall we sing the LORD\'s song in a strange land?',
    'I will praise thee with my whole heart. Thou hast magnified thy word above all thy name.',
    'O LORD, thou hast searched me and known me. I am fearfully and wonderfully made.',
    'Deliver me, O LORD, from the evil man. Keep me from the violent.',
    'LORD, I cry unto thee. Set a watch before my mouth. Keep the door of my lips.',
    'I cried unto the LORD with my voice. No man cared for my soul. Thou art my refuge.',
    'Hear my prayer, O LORD. Teach me to do thy will. Thy spirit is good.',
    'Blessed be the LORD my strength. Happy is that people whose God is the LORD.',
    'I will extol thee, my God, O king. The LORD is gracious and full of compassion. Great is the LORD.',
    'Praise ye the LORD. Praise the LORD, O my soul. Put not your trust in princes.',
    'Praise ye the LORD. He heals the broken in heart. He counts the number of the stars.',
    'Praise the LORD, O Jerusalem. He makes peace in thy borders and fills thee with the finest wheat.',
    'Praise ye the LORD from the heavens. Praise Him, sun and moon. Praise Him, all ye stars of light.',
    'Sing unto the LORD a new song. Let the saints be joyful. Let the high praises of God be in their mouth.',
    'Praise God in His sanctuary. Let everything that hath breath praise the LORD.',
  ],
  'Isaiah': [
    'The vision of Isaiah concerning Judah and Jerusalem. Israel has rebelled. Their sacrifices are meaningless without obedience.',
    'The mountain of the LORD\'s house shall be established. Nation shall not lift sword against nation. Put away idols.',
    'The LORD takes away Jerusalem\'s supply. The proud daughters of Zion will be humbled.',
    'In that day the Branch of the LORD shall be beautiful. A remnant shall be holy.',
    'The song of the vineyard. God looked for judgment and found oppression. Woe to those who call evil good.',
    'Isaiah\'s vision of the LORD high and lifted up. Seraphim cry "Holy, holy, holy." Isaiah is cleansed and commissioned: "Here am I; send me."',
    'The sign of Immanuel given to Ahaz. A virgin shall conceive and bear a son. Assyria will invade.',
    'A son is born: Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace. His government shall have no end.',
    'The LORD\'s hand is stretched out still against Israel\'s pride. Assyria is His rod of anger.',
    'Woe to the Assyrian — God\'s instrument who overreached. A remnant of Israel shall return. The LORD of hosts shall make a full end.',
    'A Rod out of the stem of Jesse. The Spirit of the LORD shall rest upon Him. The wolf shall dwell with the lamb.',
    'A song of praise. With joy shall ye draw water out of the wells of salvation.',
    'The burden of Babylon. The day of the LORD comes as destruction from the Almighty.',
    'Israel shall be restored. A taunt against the king of Babylon: "How art thou fallen from heaven, O Lucifer, son of the morning."',
    'The burden of Moab. Within three years Moab shall be destroyed.',
    'The burden of Damascus and Ephraim. Damascus will cease to be a city.',
    'Woe to the land beyond the rivers of Ethiopia. A swift messenger sent to a tall and smooth people.',
    'The burden of Egypt. The LORD rides a swift cloud into Egypt. Egypt\'s idols tremble.',
    'The sign against Egypt and Ethiopia. Isaiah walks naked and barefoot for three years as a sign.',
    'The burden of the desert of the sea. Babylon is fallen, is fallen. All her graven images are broken.',
    'The burden of the valley of vision. Jerusalem under siege. The people feast instead of repent.',
    'The burden of Tyre. The merchant city will be forgotten for seventy years.',
    'The LORD makes the earth empty. The earth is defiled under its inhabitants. A remnant sings from the ends of the earth.',
    'The LORD will swallow up death in victory. Tears will be wiped from all faces.',
    'A song of praise. Thou wilt keep him in perfect peace whose mind is stayed on thee.',
    'In that day the LORD shall punish leviathan. A song of the vineyard — every moment I water it.',
    'Woe to the proud crown of Ephraim. A foundation stone is laid in Zion. The drunkards of Ephraim will be judged.',
    'Woe to Ariel — Jerusalem. The LORD will bring distress. The wisdom of the wise shall perish.',
    'Woe to those who seek Egyptian help. In returning and rest shall ye be saved; in quietness and confidence shall be your strength.',
    'Woe to the rebellious children who take counsel not from God. In Egypt\'s shadow they trust. The LORD waits to be gracious.',
    'Behold, a king shall reign in righteousness. Women at ease, hear my voice — tremble.',
    'Woe to the spoiler. In a time of trouble, God is our salvation. The inhabitants shall say, "I am forgiven."',
    'Come near, ye nations, to hear. The sword of the LORD is filled with blood. Edom shall be desolate.',
    'The wilderness shall blossom as a rose. The ransomed of the LORD shall return to Zion with singing.',
    'Sennacherib invades Judah. Rabshakeh taunts Jerusalem. Hezekiah spreads the letter before the LORD.',
    'The LORD says to Hezekiah through Isaiah: I will defend this city. The angel of the LORD strikes 185,000 Assyrians.',
    'Hezekiah\'s illness. Isaiah tells him to set his house in order. Hezekiah prays and God adds fifteen years. Hezekiah\'s song of praise.',
    'Hezekiah shows Babylon\'s envoys all his treasures. Isaiah prophesies that everything will be carried to Babylon.',
    'Comfort ye, comfort ye my people. The voice of one crying in the wilderness. All flesh is grass, but the word of God stands forever.',
    'Who hath measured the waters in the hollow of His hand? The nations are as a drop of a bucket. They that wait upon the LORD shall renew their strength.',
    'Behold my servant. I have put my spirit upon Him. He shall bring forth judgment to the Gentiles. A bruised reed shall He not break.',
    'Fear not, for I have redeemed thee. When thou passest through the waters, I will be with thee.',
    'I am the LORD, and there is none else. I form the light and create darkness.',
    'Bel bows down, Nebo stoops. The idols of Babylon are carried on beasts. I have made and I will carry and deliver.',
    'Come down and sit in the dust, O virgin daughter of Babylon. Thy nakedness shall be uncovered.',
    'Hear this, O house of Jacob. I have refined thee in the furnace of affliction. For mine own sake I will do it.',
    'Listen, O isles. The LORD called me from the womb. He will restore Israel and be a light to the Gentiles.',
    'Can a woman forget her nursing child? I have engraved thee upon the palms of my hands.',
    'Thus saith the LORD, Where is the bill of your mother\'s divorcement? My face was set like a flint.',
    'Hearken to me, ye that follow after righteousness. Awake, awake, put on strength, O arm of the LORD.',
    'Awake, awake, put on thy beautiful garments, O Jerusalem. How beautiful are the feet of them that bring good tidings.',
    'The Suffering Servant. He is despised and rejected of men, a man of sorrows. He was wounded for our transgressions, bruised for our iniquities.',
    'Sing, O barren, thou that didst not bear. Enlarge thy tent. Every tongue that rises against thee thou shalt condemn.',
    'Ho, every one that thirsteth, come ye to the waters. Seek the LORD while He may be found.',
    'Keep justice. The sons of the stranger who join themselves to the LORD — even them will I bring to my holy mountain.',
    'The righteous perishes and no man takes it to heart. The wicked have no peace.',
    'Cry aloud, spare not. Is not this the fast that I have chosen — to loose the bands of wickedness?',
    'The LORD\'s hand is not shortened. Your iniquities have separated you from God. The Redeemer shall come to Zion.',
    'Arise, shine, for thy light is come. The Gentiles shall come to thy light. Violence shall no more be heard in thy land.',
    'The Spirit of the Lord GOD is upon me. He hath sent me to preach good tidings to the meek. The year of the LORD\'s favour.',
    'For Zion\'s sake I will not hold my peace. Thou shalt be called by a new name. A crown of glory in the hand of the LORD.',
    'Who is this that cometh from Edom? I have trodden the winepress alone. He saved them in His love and pity.',
    'Oh that thou wouldest rend the heavens and come down. We are the clay, thou art the potter.',
    'I am sought of them that asked not for me. Behold, I create new heavens and a new earth. The wolf and the lamb shall feed together.',
    'Heaven is my throne and earth my footstool. Rejoice with Jerusalem. The LORD shall come with fire.',
  ],
  'Daniel': [
    'Nebuchadnezzar besieges Jerusalem and takes captives including Daniel, Hananiah, Mishael, and Azariah. They refuse the king\'s food and God blesses them with wisdom.',
    'Nebuchadnezzar\'s dream of a great image — gold, silver, brass, iron, and clay — destroyed by a stone cut without hands. Daniel interprets: successive kingdoms ending in God\'s eternal kingdom.',
    'Nebuchadnezzar erects a golden image and commands all to worship it. Shadrach, Meshach, and Abednego refuse and are thrown into the fiery furnace. God delivers them unharmed.',
    'Nebuchadnezzar\'s dream of a great tree cut down. Daniel interprets: the king will be driven mad until he acknowledges God\'s sovereignty. It is fulfilled.',
    'Belshazzar\'s feast. A hand writes on the wall: MENE, MENE, TEKEL, UPHARSIN. Daniel interprets: the kingdom is divided and given to the Medes and Persians. Belshazzar is slain that night.',
    'Daniel is promoted under Darius. His enemies conspire to trap him through a decree against prayer. Daniel prays and is thrown into the lions\' den. God shuts the lions\' mouths.',
    'Daniel\'s vision of four great beasts from the sea — a lion, bear, leopard, and terrible beast. The Ancient of days sits in judgment. The Son of man receives everlasting dominion.',
    'Daniel\'s vision of the ram and the he-goat. Gabriel interprets: Media-Persia will be conquered by Greece, which will break into four kingdoms.',
    'Daniel prays for Jerusalem\'s restoration after reading Jeremiah. Gabriel reveals the prophecy of the seventy weeks — 490 years from the decree to rebuild Jerusalem to Messiah the Prince.',
    'Daniel fasts and prays for three weeks. A glorious man appears. The prince of Persia resisted the angel for 21 days until Michael helped.',
    'A prophecy of kings from Persia through Greece to Antiochus Epiphanes and beyond. The abomination of desolation. A time of trouble such as never was.',
    'Michael shall stand up. Many that sleep in the dust shall awake. Seal the book until the time of the end. Blessed is he that waiteth.',
  ],
  'Matthew': [
    'The genealogy of Jesus Christ from Abraham through David to Joseph. The birth of Jesus, the angel appearing to Joseph in a dream.',
    'The wise men follow the star to Bethlehem. Herod orders the slaughter of infants. Joseph flees with Mary and the child to Egypt.',
    'John the Baptist preaches repentance in the wilderness. Jesus is baptized in the Jordan and the Spirit descends like a dove.',
    'Jesus is tempted by the devil in the wilderness for forty days. He begins His ministry in Galilee and calls His first disciples.',
    'The Sermon on the Mount begins. The Beatitudes, salt and light, and Jesus teaches that He came to fulfill the Law, not destroy it.',
    'The Sermon on the Mount continues. Jesus teaches on prayer, including the Lord\'s Prayer, fasting, treasure in heaven, and not serving two masters.',
    'The Sermon on the Mount concludes. Judge not, ask and receive, the narrow gate, false prophets, and building on the rock versus sand.',
    'Jesus cleanses a leper, heals the centurion\'s servant, calms the storm, and casts demons into a herd of swine in Gadara.',
    'Jesus heals a paralytic lowered through the roof, calls Matthew the tax collector, and teaches about new wine in old wineskins.',
    'Jesus sends out the twelve apostles with authority to heal and preach. He warns them of persecution and promises God\'s care.',
    'John the Baptist sends disciples to ask if Jesus is the Messiah. Jesus pronounces woe on unrepentant cities and invites the weary to come to Him.',
    'Jesus defends His disciples for picking grain on the Sabbath. He heals a man with a withered hand and the Pharisees plot against Him.',
    'The parable of the sower and the soils. Jesus explains the parable to the disciples and teaches the parables of the tares, mustard seed, and hidden treasure.',
    'Herod beheads John the Baptist. Jesus feeds five thousand with five loaves and two fishes. He walks on the water to the disciples\' boat.',
    'The Pharisees question Jesus about handwashing traditions. Jesus teaches that defilement comes from the heart. He heals the Canaanite woman\'s daughter.',
    'The Pharisees and Sadducees demand a sign. Peter confesses Jesus as the Christ. Jesus foretells His death and resurrection.',
    'The transfiguration on the mountain with Moses and Elijah. Jesus heals a demon-possessed boy and teaches about the Temple tax.',
    'Jesus teaches on greatness in the kingdom, stumbling blocks, the lost sheep, and forgiveness. The parable of the unforgiving servant.',
    'Jesus teaches on divorce and remarriage. He blesses little children. The rich young ruler asks about eternal life and goes away sorrowful.',
    'The parable of the laborers in the vineyard. James and John\'s mother asks for her sons to sit at Jesus\' right and left hand.',
    'The triumphal entry into Jerusalem on a donkey. Jesus cleanses the Temple, overturning the money changers\' tables.',
    'The parable of the two sons and the parable of the wicked tenants. The Pharisees and chief priests seek to arrest Jesus.',
    'The parable of the wedding feast. Questions about paying taxes to Caesar, the resurrection, and the greatest commandment.',
    'Jesus pronounces seven woes on the scribes and Pharisees. He laments over Jerusalem.',
    'The Olivet Discourse: Jesus foretells the destruction of the Temple and the signs of His coming. The parable of the fig tree.',
    'Parables of the ten virgins and the talents. The judgment of the nations — separating sheep from goats.',
    'The plot to kill Jesus. Mary anoints Him at Bethany. Judas agrees to betray Him. The Last Supper and institution of the Lord\'s Supper.',
    'Jesus is arrested in Gethsemane. He is tried before Caiaphas and the Sanhedrin. Peter denies Jesus three times.',
  ],
  'Mark': [
    'John the Baptist prepares the way. Jesus is baptized and tempted. He calls His first disciples and heals a man with an unclean spirit in Capernaum.',
    'Jesus heals a paralytic lowered through the roof. He calls Levi the tax collector and teaches about fasting and the Sabbath.',
    'Jesus heals a man with a withered hand on the Sabbath. He appoints the twelve apostles and is accused of casting out demons by Beelzebub.',
    'The parable of the sower. Jesus calms the storm on the Sea of Galilee.',
    'Jesus heals the Gadarene demoniac and sends the demons into swine. He heals the woman with the issue of blood and raises Jairus\'s daughter.',
    'Jesus is rejected at Nazareth. He sends out the twelve two by two. Herod beheads John the Baptist. Jesus feeds five thousand.',
    'Jesus walks on water. The Pharisees question Him about handwashing traditions. He teaches that defilement comes from the heart.',
    'Jesus feeds four thousand. The Pharisees demand a sign. Peter confesses Jesus as the Christ. Jesus foretells His death.',
    'The transfiguration. Jesus heals a demon-possessed boy. He teaches about greatness and warns against causing others to stumble.',
    'Jesus teaches on divorce. He blesses children and speaks with the rich young man. He foretells His death a third time.',
    'The triumphal entry into Jerusalem. Jesus curses the fig tree and cleanses the Temple.',
    'The authority of Jesus questioned. The parable of the wicked tenants. Questions about taxes, resurrection, and the greatest commandment.',
    'The Olivet Discourse: Jesus foretells the destruction of the Temple, the abomination of desolation, and His second coming.',
    'Jesus is anointed at Bethany. The Last Supper. Jesus prays in Gethsemane and is arrested. He is tried before the Sanhedrin.',
    'Jesus before Pilate. Barabbas released. Jesus is scourged, mocked, and crucified. He dies and is buried by Joseph of Arimathea.',
    'The women find the tomb empty. An angel announces the resurrection. Jesus appears to Mary Magdalene and the disciples.',
  ],
  'Luke': [
    'Luke\'s introduction and purpose. The angel Gabriel announces the birth of John the Baptist to Zacharias in the Temple.',
    'The angel Gabriel announces to Mary that she will bear the Son of God. Mary visits Elizabeth. Mary\'s Magnificat. The birth of John the Baptist.',
    'The birth of Jesus in Bethlehem. Angels announce to shepherds. Jesus is presented in the Temple. Simeon and Anna prophesy over Him.',
    'John the Baptist preaches repentance and baptizes. Jesus is baptized. The genealogy of Jesus traced back to Adam.',
    'Jesus is tempted by the devil in the wilderness. He teaches in the synagogue at Nazareth and is rejected. He heals and casts out demons in Capernaum.',
    'Jesus calls Peter after a miraculous catch of fish. He heals a leper, a paralytic, and calls Levi. He teaches about fasting.',
    'Jesus heals on the Sabbath. He chooses the twelve apostles. The Sermon on the Plain: blessings and woes.',
    'Jesus heals the centurion\'s servant and raises the widow\'s son at Nain. John the Baptist sends disciples to Jesus. A sinful woman anoints Jesus\' feet.',
    'The parable of the sower. Jesus calms the storm, heals the Gadarene demoniac, heals the woman with the issue of blood, and raises Jairus\'s daughter.',
    'Jesus sends out the twelve. He feeds five thousand. Peter\'s confession. Jesus foretells His death and is transfigured on the mountain.',
    'Jesus sends out the seventy. The parable of the Good Samaritan. Mary and Martha.',
    'Jesus teaches the disciples to pray. He casts out a demon and warns against the sign of Jonah. He pronounces woes on the Pharisees.',
    'Jesus warns against hypocrisy and covetousness. The parable of the rich fool. Jesus teaches on anxiety, watchfulness, and preparedness.',
    'Jesus calls for repentance. The parable of the barren fig tree. He heals a woman on the Sabbath and teaches about the narrow door.',
    'Jesus heals a man with dropsy on the Sabbath. Parables of the great banquet and the cost of discipleship.',
    'The parables of the lost sheep, the lost coin, and the prodigal son.',
    'The parable of the unjust steward. Jesus teaches on faithfulness, divorce, and the rich man and Lazarus.',
    'Jesus teaches on forgiveness, faith, and duty. He heals ten lepers — only one returns to give thanks.',
    'The parable of the persistent widow. The Pharisee and the tax collector. Jesus blesses children and speaks with the rich ruler.',
    'Jesus heals blind Bartimaeus near Jericho. Zacchaeus the tax collector receives Jesus. The parable of the ten minas.',
    'The triumphal entry. Jesus weeps over Jerusalem and cleanses the Temple.',
    'Jesus\' authority questioned. The parable of the wicked tenants. Questions about taxes to Caesar, the resurrection, and David\'s son.',
    'Jesus warns about the scribes. The widow\'s two mites. The Olivet Discourse: signs before the end.',
    'The Last Supper. Jesus is betrayed and arrested. Peter denies Him. Jesus is tried before the Sanhedrin.',
  ],
  'John': [
    'In the beginning was the Word. The Word was God and became flesh. John the Baptist testifies. Jesus calls His first disciples.',
    'The wedding at Cana — Jesus turns water into wine. He cleanses the Temple in Jerusalem.',
    'Nicodemus visits Jesus at night. Jesus teaches about being born again. John the Baptist\'s final testimony.',
    'Jesus speaks with the Samaritan woman at the well. He reveals Himself as the Messiah. He heals the nobleman\'s son.',
    'Jesus heals the man at the Pool of Bethesda on the Sabbath. He defends His authority as the Son of God.',
    'Jesus feeds five thousand with five loaves and two fishes. He walks on water. He teaches "I am the bread of life." Many disciples leave.',
    'Jesus teaches at the Feast of Tabernacles. Division among the people. "If any man thirst, let him come unto me and drink."',
    'The woman caught in adultery. Jesus declares "I am the light of the world." He debates with the Pharisees about Abraham.',
    'Jesus heals a man born blind. The Pharisees investigate and cast the man out of the synagogue. Jesus finds him and reveals Himself.',
    'The Good Shepherd discourse. Jesus at the Feast of Dedication. "I and my Father are one." The Jews try to stone Him.',
    'The death and raising of Lazarus at Bethany. Caiaphas prophesies that one man should die for the nation.',
    'Mary anoints Jesus\' feet with costly spikenard. The triumphal entry. Greeks seek Jesus. He teaches about His coming death.',
    'Jesus washes the disciples\' feet at the Last Supper. He predicts Judas\'s betrayal and gives the new commandment to love one another.',
    'Jesus comforts the disciples. "I am the way, the truth, and the life." He promises the Holy Spirit, the Comforter.',
    'Jesus teaches "I am the true vine." He warns of the world\'s hatred and promises the Spirit of truth.',
    'Jesus tells the disciples of coming persecution. He promises the Holy Spirit will guide them into all truth. "In the world ye shall have tribulation."',
    'Jesus\' high priestly prayer. He prays for Himself, for the disciples, and for all who will believe through their word.',
    'Jesus is arrested in the garden. He is taken to Annas, then Caiaphas. Peter denies Him. Jesus is brought before Pilate.',
    'Pilate finds no fault in Jesus but yields to the crowd. Jesus is scourged, crowned with thorns, and crucified. He dies and is buried.',
    'Mary Magdalene finds the tomb empty. Jesus appears to her and to the disciples. Thomas believes when he sees the risen Lord.',
    'Jesus appears at the Sea of Galilee. The miraculous catch of fish. Jesus restores Peter three times and commissions him to feed His sheep.',
  ],
  'Acts': [
    'Jesus ascends to heaven from the Mount of Olives. The disciples choose Matthias to replace Judas.',
    'The Holy Spirit falls at Pentecost. The disciples speak in tongues. Peter preaches and three thousand are saved.',
    'Peter and John heal the lame man at the Beautiful Gate. Peter preaches in Solomon\'s Porch.',
    'Peter and John are arrested by the Sadducees. They testify before the Sanhedrin. The believers pray for boldness.',
    'Ananias and Sapphira lie about their offering and are struck dead. The apostles perform many signs and are arrested again.',
    'Seven deacons are chosen, including Stephen. Stephen is accused of blasphemy and brought before the Sanhedrin.',
    'Stephen\'s defense before the Sanhedrin — a survey of Israel\'s history. He is stoned to death. Saul watches approvingly.',
    'The church is scattered by persecution. Philip preaches in Samaria and baptizes the Ethiopian eunuch on the road to Gaza.',
    'Saul\'s conversion on the road to Damascus. Ananias restores his sight. Saul begins preaching that Jesus is the Son of God.',
    'Peter has a vision of unclean animals and is sent to Cornelius the centurion. The Holy Spirit falls on the Gentiles.',
    'Peter defends his visit to Cornelius before the Jerusalem church. The gospel spreads to Antioch. Barnabas and Saul minister there.',
    'Herod Agrippa kills James and imprisons Peter. An angel frees Peter. Herod is struck dead for accepting worship.',
    'Barnabas and Saul are sent out from Antioch on the first missionary journey. They preach in Cyprus and Pisidian Antioch.',
    'Paul and Barnabas preach in Iconium, Lystra, and Derbe. Paul is stoned at Lystra and left for dead. They return to Antioch.',
    'The Jerusalem Council debates whether Gentile believers must be circumcised. James issues the decision: Gentiles are not bound by the ceremonial law.',
    'Paul and Silas begin the second missionary journey. Timothy joins them. Paul receives the Macedonian call. Lydia is converted and the Philippian jailer is saved.',
    'Paul preaches in Thessalonica and Berea. In Athens he addresses the Areopagus, declaring the unknown God.',
    'Paul in Corinth for eighteen months. He is brought before Gallio the proconsul. He returns to Antioch via Ephesus.',
    'Paul\'s third missionary journey. Apollos preaches in Ephesus. Paul baptizes disciples of John. A riot erupts over the silversmiths\' trade.',
    'Paul travels through Macedonia and Greece. He raises Eutychus at Troas. He meets with the Ephesian elders at Miletus.',
    'Paul travels to Jerusalem despite warnings. He meets James and the elders. He is seized in the Temple by a mob.',
    'Paul addresses the crowd from the stairs of the Antonia Fortress. He reveals his Roman citizenship to avoid scourging.',
    'Paul before the Sanhedrin. The Lord appears to him at night. A conspiracy to kill Paul is discovered. He is transferred to Caesarea.',
    'Paul is accused before Felix the governor. He defends himself. Felix keeps him imprisoned for two years.',
    'Paul appeals to Caesar before Festus. King Agrippa and Bernice arrive. Festus presents Paul\'s case.',
    'Paul defends himself before Agrippa, recounting his conversion. Agrippa says Paul almost persuades him to be a Christian.',
    'Paul sails for Rome. A violent storm shipwrecks them on Malta. All 276 passengers survive.',
    'Paul arrives in Rome. He meets with Jewish leaders and preaches the kingdom of God. He lives under house arrest for two years, teaching all who come.',
  ],
  'Romans': [
    'Paul\'s greeting and desire to visit Rome. The gospel is the power of God for salvation. God\'s wrath is revealed against ungodliness.',
    'God\'s righteous judgment. The Jews are not exempt. Circumcision of the heart matters more than circumcision of the flesh.',
    'All have sinned and fall short. No one is justified by works of the law. Righteousness comes through faith in Jesus Christ.',
    'Abraham was justified by faith, not works. His faith was counted as righteousness before circumcision. He is the father of all who believe.',
    'Being justified by faith we have peace with God. Where sin abounded, grace abounded much more.',
    'Shall we continue in sin? God forbid. We are dead to sin and alive to God. Sin shall not have dominion over you.',
    'The law reveals sin but cannot save. Paul describes the inner conflict: the good I would I do not, the evil I would not, that I do.',
    'No condemnation for those in Christ Jesus. The Spirit gives life. Nothing can separate us from the love of God.',
    'Paul\'s anguish for Israel. God\'s sovereign choice: Jacob over Esau, mercy on whom He will.',
    'Israel pursued righteousness by the law and missed it. Salvation comes by confessing with the mouth and believing in the heart.',
    'God has not cast away Israel. A remnant remains by grace. The fullness of the Gentiles will come, and all Israel shall be saved.',
    'Present your bodies as a living sacrifice. Be transformed by the renewing of your mind. The body of Christ has many members with different gifts.',
    'Submit to governing authorities. Love fulfills the law. Put on the Lord Jesus Christ.',
    'The strong and the weak in faith. Do not judge your brother over food or holy days. We shall all stand before the judgment seat of Christ.',
    'Bear one another\'s burdens. Christ ministered to both Jew and Gentile. Paul\'s plans to visit Rome on his way to Spain.',
    'Paul commends Phoebe and greets many by name. He warns against those who cause divisions. Final greetings and doxology.',
  ],
  'Revelation': [
    'The revelation of Jesus Christ given to John on Patmos. A vision of Christ among seven golden candlesticks.',
    'Letters to Ephesus (lost first love), Smyrna (persecution), Pergamos (compromise), and Thyatira (tolerance of Jezebel).',
    'Letters to Sardis (dead reputation), Philadelphia (open door), and Laodicea (lukewarm, neither hot nor cold).',
    'John sees an open door in heaven. The throne of God, twenty-four elders, four living creatures, and ceaseless worship.',
    'A scroll sealed with seven seals. The Lamb that was slain is worthy to open it. All creation worships the Lamb.',
    'The first six seals opened: white horse, red horse, black horse, pale horse, martyrs under the altar, and a great earthquake.',
    'Four angels hold the winds. 144,000 are sealed from the twelve tribes. A great multitude from every nation stands before the throne.',
    'The seventh seal — silence in heaven for half an hour. Seven angels receive seven trumpets. The first four trumpets sound.',
    'The fifth and sixth trumpets. Locusts from the bottomless pit. An army of 200 million horsemen. Mankind still does not repent.',
    'A mighty angel with a little book. John eats the book — sweet in the mouth, bitter in the stomach.',
    'Two witnesses prophesy for 1,260 days, are killed, and rise again. The seventh trumpet: the kingdoms of this world become the kingdoms of our Lord.',
    'The woman clothed with the sun and the dragon. War in heaven — Michael casts out Satan. The dragon persecutes the woman.',
    'The beast from the sea with seven heads and ten horns. The beast from the earth with two horns. The mark of the beast — 666.',
    'The Lamb on Mount Zion with 144,000. Three angels proclaim judgment. The harvest of the earth and the winepress of God\'s wrath.',
    'Seven angels with seven plagues — the last, for in them the wrath of God is complete.',
    'The seven bowls of wrath poured out: sores, sea of blood, rivers of blood, scorching sun, darkness, Euphrates dried, great earthquake and hail.',
    'The great harlot Babylon sitting on many waters and on a scarlet beast. The mystery of Babylon explained.',
    'Babylon is fallen. Come out of her, my people. The merchants of the earth weep over her destruction.',
    'The marriage supper of the Lamb. Christ returns on a white horse — King of Kings and Lord of Lords. The beast and false prophet cast into the lake of fire.',
    'Satan is bound for a thousand years. The first resurrection. After the thousand years, Satan is loosed and defeated. The great white throne judgment.',
    'A new heaven and a new earth. The New Jerusalem descends from God. God shall wipe away all tears. There shall be no more death.',
    'The river of the water of life and the tree of life. Jesus says "I come quickly." The Spirit and the bride say "Come." Even so, come, Lord Jesus.',
  ],
}

// Add remaining NT books
const NT_EXTRAS: Record<string, string[]> = {
  '1 Corinthians': ['Paul addresses divisions in the Corinthian church. Christ is not divided. God chose the foolish things to shame the wise.','Paul determined to know nothing among them except Christ crucified. The Spirit reveals the deep things of God.','The Corinthians are spiritual infants. Ministers are fellow workers. The foundation is Jesus Christ.','Apostles are servants of Christ and stewards of mysteries. Paul warns against pride.','A case of sexual immorality must be dealt with. Purge out the old leaven.','Lawsuits between believers are shameful. The body is the temple of the Holy Spirit.','Paul addresses marriage and singleness. Each should remain in their calling.','Meat offered to idols. Knowledge puffs up but love builds up.','Paul defends his apostleship. A worker is worthy of his wages.','Warnings from Israel\'s history. Flee idolatry. Do all to the glory of God.','Head coverings in worship. The Lord\'s Supper — correcting abuse of communion.','Spiritual gifts — varieties of gifts but the same Spirit. The body has many members.','The love chapter. Without love, gifts are nothing. Love is patient, kind, does not envy. The greatest is love.','Prophecy is greater than tongues in assembly. Let all things be done decently and in order.','The resurrection of Christ is the gospel\'s foundation. If Christ is not risen, faith is vain. Victory over death.','The collection for the saints. Paul\'s travel plans. Watch, stand fast, be strong. Maranatha.'],
  '2 Corinthians': ['The God of all comfort comforts us so we can comfort others. Paul explains his delayed visit.','Paul urges forgiveness for the repentant offender. The triumph of Christ.','The Corinthians are Paul\'s letter on hearts. The ministry of the Spirit gives life.','Treasure in earthen vessels. Though outwardly wasting, inwardly renewed. Light affliction works eternal glory.','We walk by faith, not sight. Absent from body, present with the Lord.','Be not unequally yoked. Come out and be separate. God will dwell among His people.','Paul\'s joy over their repentance. Godly sorrow produces repentance; worldly sorrow produces death.','The generosity of Macedonian churches. Christ became poor that we might become rich.','God loves a cheerful giver. He who sows bountifully reaps bountifully.','Paul defends his ministry. Our weapons are not carnal but mighty through God.','Paul boasts of sufferings. Caught up to the third heaven. His thorn in the flesh. God\'s grace is sufficient.','Paul plans his third visit. He warns the unrepentant.','Final warnings. Be of good comfort. The grace of the Lord Jesus Christ be with you all.'],
  'Galatians': ['Paul defends his apostleship. The gospel was received by revelation of Jesus Christ.','Paul confronts Peter at Antioch. Justified by faith, not works of the law.','Abraham believed God — counted as righteousness. The law was a schoolmaster to bring us to Christ.','God sent His Son to redeem those under law. We are sons, not slaves.','Stand fast in liberty. Walk in the Spirit. The fruit of the Spirit.','Bear one another\'s burdens. A man reaps what he sows. Paul glories only in the cross.'],
  'Ephesians': ['Spiritual blessings in Christ. Chosen before the foundation of the world. Sealed with the Holy Spirit.','Dead in sins, made alive in Christ. By grace saved through faith — not of works. God\'s workmanship.','The mystery revealed: Gentiles are fellow heirs. Paul prays to comprehend the love of Christ.','Walk worthy. One body, one Spirit, one Lord, one faith. Christ gave gifts for building up.','Walk in love. No fellowship with darkness. Wives submit; husbands love as Christ loved the church.','Children obey parents. The whole armor of God: truth, righteousness, faith, salvation, the sword of the Spirit.'],
  'Philippians': ['Paul\'s thanksgiving. His imprisonment advances the gospel. To live is Christ, to die is gain.','Let this mind be in you which was in Christ — He humbled Himself unto death. Work out salvation with fear and trembling.','Paul counts all loss for knowing Christ. He presses toward the mark for the prize.','Rejoice always. Be anxious for nothing. The peace of God guards your hearts. I can do all things through Christ.'],
  'Colossians': ['Christ is the image of the invisible God, firstborn of all creation. By Him all things were created.','Beware philosophy and vain deceit. In Christ dwells the fullness of the Godhead bodily.','Set affections above. Put off the old man, put on the new. Wives, husbands, children instructed.','Masters, be just. Continue in prayer. Walk in wisdom. Final greetings.'],
  '1 Thessalonians': ['Paul thanks God for their faith, love, and hope. They received the word with joy of the Holy Spirit.','Paul recalls his ministry — not with flattery but as a nursing mother and encouraging father.','Timothy\'s report of their faith brings comfort. Paul prays to see them again.','Instructions on holiness. Those who died in Christ will rise first.','The day of the Lord comes as a thief. We are children of light. Rejoice always, pray without ceasing.'],
  '2 Thessalonians': ['Paul commends their growing faith amid persecution. God will repay those who trouble them.','The day of the Lord has not yet come. The man of sin must be revealed first.','Paul commands the idle to work. If any will not work, neither shall he eat.'],
  '1 Timothy': ['Paul warns against false teachers. The law is good if used lawfully. Paul recounts his own conversion.','Instructions on prayer for all people. God desires all to be saved.','Qualifications for bishops and deacons.','In latter times some depart from faith. Timothy should be an example.','Instructions on widows, elders, and personal conduct.','Godliness with contentment is great gain. The love of money is the root of all evil. Fight the good fight.'],
  '2 Timothy': ['Fan into flame God\'s gift. God gave not fear but power, love, and a sound mind.','Be strong in grace. Study to show thyself approved, rightly dividing the word of truth.','Perilous times in the last days. Continue in the Scriptures which make wise unto salvation.','Preach the word in season and out. Paul has fought the good fight. A crown of righteousness awaits.'],
  'Titus': ['Paul left Titus in Crete. Qualifications for elders. Rebuke false teachers.','Teach sound doctrine to all ages. The grace of God teaches us to live soberly.','Submit to authorities. Maintain good works. Avoid foolish controversies.'],
  'Philemon': ['Paul appeals for Onesimus, a runaway slave now a believer. Receive him back as a brother.'],
  'Hebrews': ['God spoke by His Son, who is the brightness of His glory. The Son is superior to angels.','Do not neglect so great a salvation. Jesus was made lower than angels for the suffering of death.','Jesus is greater than Moses. Harden not your hearts as in the wilderness.','A rest remains for God\'s people. The word of God is living, sharper than any two-edged sword.','Jesus our great High Priest sympathizes with our weaknesses. Called after the order of Melchizedek.','Warning against falling away. God\'s promise to Abraham is sure.','Melchizedek was greater than Abraham. Jesus is priest forever — a better priesthood than Aaron\'s.','Christ mediates a better covenant on better promises. The first covenant is made old.','The earthly tabernacle described. Christ entered the heavenly tabernacle with His own blood.','Blood of bulls and goats cannot take away sin. Christ offered one sacrifice forever. Draw near with a true heart.','The faith chapter. By faith Abel, Enoch, Noah, Abraham, Moses, Rahab, and many others.','Lay aside every weight. Run with patience. God chastens whom He loves. Sinai vs. Zion.','Let brotherly love continue. Marriage is honorable. Jesus Christ the same yesterday, today, and forever.'],
  'James': ['Count it joy in trials. Ask God for wisdom. The rich fade away. Blessed is he who endures temptation.','Show no partiality. Faith without works is dead. Abraham was justified by works when he offered Isaac.','The tongue is a fire. No man can tame it. Wisdom from above is pure, peaceable, gentle.','Wars come from lusts. Submit to God, resist the devil. Your life is a vapor.','Woe to the rich who defraud. Be patient for the Lord\'s coming. The prayer of faith saves the sick.'],
  '1 Peter': ['Born again to a living hope through the resurrection. Be holy as God is holy.','Desire the pure milk of the word. A chosen generation, a royal priesthood. Submit to authority.','Wives submit; husbands dwell with knowledge. Do not return evil for evil. Christ suffered, the just for the unjust.','Since Christ suffered, arm yourselves likewise. The end of all things is at hand. Judgment begins at God\'s house.','Elders, shepherd the flock. Humble yourselves under God\'s mighty hand. The devil walks about as a roaring lion.'],
  '2 Peter': ['Add to faith virtue, knowledge, temperance, patience, godliness, kindness, charity. Peter was an eyewitness of Christ\'s majesty.','False teachers bring damnable heresies. God spared not angels that sinned, nor the old world, nor Sodom.','Scoffers ask "Where is His coming?" One day is as a thousand years. The heavens shall pass away. Be diligent.'],
  '1 John': ['That which was from the beginning — we have seen and handled. God is light. If we confess, He forgives.','Jesus is our advocate. He who says he knows God and keeps not His commandments is a liar. Love not the world.','Behold what love the Father has given us. We shall be like Him. He who sins is of the devil.','Test the spirits. Every spirit confessing Jesus Christ in the flesh is of God. God is love. Perfect love casts out fear.','Whoever believes Jesus is the Christ is born of God. This is the victory — our faith. God has given us eternal life.'],
  '2 John': ['Walk in truth and love. Many deceivers deny Christ is come in the flesh. Do not receive them.'],
  '3 John': ['Commendation for Gaius\'s hospitality. Diotrephes loves preeminence. Demetrius has a good report.'],
  'Jude': ['Contend for the faith. False teachers have crept in. Examples of judgment: Israel, fallen angels, Sodom. Keep yourselves in God\'s love.'],
}
Object.assign(CHAPTER_SUMMARIES, NT_EXTRAS)

/**
 * Returns the chapter summary for a given book and chapter (1-based).
 * Returns null if no summary is available.
 */
export function getChapterSummary(book: string, chapter: number): string | null {
  const summaries = CHAPTER_SUMMARIES[book]
  if (!summaries || chapter < 1 || chapter > summaries.length) return null
  return summaries[chapter - 1]
}
